//
// Created by juanr on 12/3/2018.
//

#ifndef VETERINARIA_CONST_H
#define VETERINARIA_CONST_H

#define MAX_SOCIOS 1000
#define MIN_MASCOTAS 1
#define MAX_MASCOTAS 10
#define MAX_CONSULTAS 20
#define FACTOR_ALIMENTO_GATO 0.015
#define FACTOR_ALIMENTO_PERRO 0.025

#endif //VETERINARIA_CONST_H
